version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  etherpad:
    depends_on:
      - db
    build:
      context: .
      args:
        tag: 'acesandaros/etherpad'
        ETHERPAD_PLUGINS: 'ep_comments_page ep_author_neat'
    image: acesandaros/etherpad:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - '9001:9001'

volumes:
  db_data: {}
